// frontend/src/components/Chat/ChatMessage.vue
<template>
  <div class="chat-message" :class="[`role-${message.role}`]">
    <div class="avatar">
      {{ message.role === 'user' ? 'U' : 'AI' }}
    </div>
    <div class="content">
      <div class="text">{{ message.content }}</div>
      <div v-if="message.sources && message.sources.length > 0" class="sources">
        <div class="sources-label">Sources:</div>
        <div
          v-for="source in message.sources"
          :key="source.id"
          class="source-item"
        >
          {{ source.title }}
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Message } from '@shared/types/chat'

defineProps<{
  message: Message
}>()
</script>

<style scoped>
.chat-message {
  display: flex;
  gap: 12px;
  align-items: flex-start;
}

.avatar {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 12px;
  font-weight: 600;
  flex-shrink: 0;
}

.role-user .avatar {
  background: var(--color-primary);
  color: white;
}

.role-assistant .avatar {
  background: #10b981;
  color: white;
}

.content {
  flex: 1;
  min-width: 0;
}

.text {
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  padding: 12px 16px;
  font-size: 14px;
  line-height: 1.6;
}

.role-user .text {
  background: var(--color-primary);
  border-color: var(--color-primary);
  color: white;
}

.sources {
  margin-top: 8px;
  padding: 8px 12px;
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  font-size: 12px;
}

.sources-label {
  font-weight: 600;
  margin-bottom: 4px;
  color: var(--color-text-secondary);
}

.source-item {
  padding: 2px 0;
  color: var(--color-primary);
}
</style>

// frontend/components/chat/ChatMessage.tsx
import { User, Bot } from 'lucide-react'
import { clsx } from 'clsx'

interface MessageItem {
  id: string
  role: 'user' | 'assistant' | 'system'
  content: string
  timestamp: number
  sources?: Array<{
    doc_id: string
    chunk_id?: string
    title?: string
    content?: string
    score?: number
  }>
}

interface ChatMessageProps {
  message: MessageItem
}

export function ChatMessage({ message }: ChatMessageProps) {
  const isUser = message.role === 'user'

  return (
    <div className={clsx('flex gap-3', isUser && 'flex-row-reverse')}>
      <div
        className={clsx(
          'w-8 h-8 rounded-full flex items-center justify-center shrink-0 text-xs font-semibold',
          isUser ? 'bg-primary text-white' : 'bg-emerald-500 text-white'
        )}
      >
        {isUser ? <User size={16} /> : <Bot size={16} />}
      </div>

      <div className={clsx('flex flex-col gap-1 max-w-[75%]', isUser && 'items-end')}>
        <div
          className={clsx(
            'rounded-lg px-4 py-3 text-sm leading-relaxed',
            isUser
              ? 'bg-primary text-white rounded-tr-none'
              : 'bg-white border border-border rounded-tl-none'
          )}
        >
          <p className="whitespace-pre-wrap">{message.content}</p>
        </div>

        {message.sources && message.sources.length > 0 && (
          <div className="bg-white border border-border rounded-lg px-3 py-2 text-xs">
            <p className="font-semibold text-foreground-secondary mb-1">Sources:</p>
            {message.sources.map((source, i) => (
              <p key={i} className="text-primary">
                {source.title || source.doc_id}
              </p>
            ))}
          </div>
        )}
      </div>
    </div>
  )
}
