// rag_system/frontend/src/components/Document/DocumentList.vue
<template>
  <div class="document-list">
    <div v-if="loading" class="loading">Loading...</div>
    <div v-else-if="documents.length === 0" class="empty">
      No documents uploaded yet.
    </div>
    <div v-else class="list">
      <div
        v-for="doc in documents"
        :key="doc.id"
        class="document-item"
      >
        <div class="doc-info">
          <div class="doc-title">{{ doc.filename }}</div>
          <div class="doc-meta">
            {{ formatDate(doc.uploadedAt) }} &middot; {{ formatSize(doc.size) }}
          </div>
        </div>
        <button class="btn-delete" @click="handleDelete(doc.id)">
          Delete
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { documentApi } from '@/api'
import type { DocumentInfo } from '@shared/types/document'

const documents = ref<DocumentInfo[]>([])
const loading = ref(false)

async function refresh() {
  loading.value = true
  try {
    const data = await documentApi.list()
    documents.value = data.documents || []
  } catch (e) {
    console.error('Failed to load documents:', e)
  } finally {
    loading.value = false
  }
}

async function handleDelete(id: string) {
  try {
    await documentApi.delete(id)
    await refresh()
  } catch (e) {
    console.error('Delete failed:', e)
  }
}

function formatDate(ts: number) {
  return new Date(ts).toLocaleDateString()
}

function formatSize(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`
}

defineExpose({ refresh })

onMounted(() => {
  refresh()
})
</script>

<style scoped>
.loading,
.empty {
  text-align: center;
  color: var(--color-text-secondary);
  padding: 32px;
}

.list {
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.document-item {
  display: flex;
  justify-content: space-between;
  align-items: center;
  background: var(--color-bg);
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  padding: 12px 16px;
}

.doc-title {
  font-weight: 500;
  margin-bottom: 2px;
}

.doc-meta {
  font-size: 12px;
  color: var(--color-text-secondary);
}

.btn-delete {
  padding: 6px 12px;
  color: #ef4444;
  border: 1px solid #ef4444;
  border-radius: var(--radius);
  font-size: 13px;
}

.btn-delete:hover {
  background: #fef2f2;
}
</style>

// frontend/components/document/DocumentList.tsx
'use client'

import { useEffect, useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { documentApi, type DocumentInfo } from '@/lib/api'
import { Trash2 } from 'lucide-react'
import { clsx } from 'clsx'

function formatDate(ts: number) {
  return new Date(ts).toLocaleDateString()
}

function formatSize(bytes: number) {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / 1024 / 1024).toFixed(1)} MB`
}

export function DocumentList() {
  const queryClient = useQueryClient()

  const { data, isLoading, error } = useQuery({
    queryKey: ['documents'],
    queryFn: documentApi.list,
  })

  const deleteMutation = useMutation({
    mutationFn: documentApi.delete,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['documents'] })
    },
  })

  return (
    <div>
      {isLoading && <p className="text-foreground-secondary text-sm">Loading...</p>}
      {error && <p className="text-red-500 text-sm">Failed to load documents</p>}

      {!isLoading && data?.documents.length === 0 && (
        <p className="text-foreground-secondary text-sm text-center py-8">
          No documents uploaded yet.
        </p>
      )}

      {data?.documents && data.documents.length > 0 && (
        <div className="flex flex-col gap-2">
          {data.documents.map((doc: DocumentInfo) => (
            <div
              key={doc.id}
              className="flex items-center justify-between bg-white border border-border rounded-lg px-4 py-3"
            >
              <div>
                <p className="font-medium">{doc.filename}</p>
                <p className="text-xs text-foreground-secondary">
                  {formatDate(doc.uploaded_at)} &middot; {formatSize(doc.size)}
                </p>
              </div>
              <button
                onClick={() => deleteMutation.mutate(doc.id)}
                disabled={deleteMutation.isPending}
                className={clsx(
                  'p-2 rounded-lg text-red-500 hover:bg-red-50 transition-colors',
                  deleteMutation.isPending && 'opacity-50 cursor-not-allowed'
                )}
              >
                <Trash2 size={16} />
              </button>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
