// frontend/components/chat/ChatInput.tsx
'use client'

import { useState, useRef, useEffect, KeyboardEvent } from 'react'
import { Send } from 'lucide-react'
import { clsx } from 'clsx'

interface ChatInputProps {
  disabled?: boolean
  onSubmit: (content: string) => void
}

export function ChatInput({ disabled, onSubmit }: ChatInputProps) {
  const [value, setValue] = useState('')
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  function handleSubmit() {
    if (!value.trim() || disabled) return
    onSubmit(value.trim())
    setValue('')

    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto'
    }
  }

  function handleKeyDown(e: KeyboardEvent<HTMLTextAreaElement>) {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSubmit()
    }
  }

  function handleChange(e: React.ChangeEvent<HTMLTextAreaElement>) {
    setValue(e.target.value)

    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto'
      textareaRef.current.style.height = `${textareaRef.current.scrollHeight}px`
    }
  }

  useEffect(() => {
    if (textareaRef.current && value === '') {
      textareaRef.current.style.height = 'auto'
    }
  }, [value])

  return (
    <div className="flex gap-2 items-end bg-white border border-border rounded-lg p-2">
      <textarea
        ref={textareaRef}
        value={value}
        onChange={handleChange}
        onKeyDown={handleKeyDown}
        disabled={disabled}
        placeholder="Type your message..."
        rows={1}
        className={clsx(
          'flex-1 resize-none px-3 py-2 text-sm bg-transparent',
          'focus:outline-none min-h-[40px] max-h-[200px]',
          'disabled:opacity-50 disabled:cursor-not-allowed'
        )}
        style={{ height: 'auto' }}
      />
      <button
        onClick={handleSubmit}
        disabled={disabled || !value.trim()}
        className={clsx(
          'shrink-0 w-10 h-10 flex items-center justify-center rounded-lg transition-colors',
          'bg-primary text-white hover:bg-primary-hover',
          'disabled:opacity-50 disabled:cursor-not-allowed'
        )}
      >
        <Send size={18} />
      </button>
    </div>
  )
}

// rag_system/frontend/src/components/Chat/ChatInput.vue
<template>
  <div class="chat-input">
    <textarea
      v-model="input"
      class="input-field"
      placeholder="Type your message..."
      :disabled="disabled"
      @keydown.enter.exact.prevent="handleSubmit"
      rows="1"
    />
    <button
      class="btn-send"
      @click="handleSubmit"
      :disabled="disabled || !input.trim()"
    >
      Send
    </button>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'

defineProps<{
  disabled?: boolean
}>()

const emit = defineEmits<{
  submit: [content: string]
}>()

const input = ref('')

function handleSubmit() {
  if (!input.value.trim()) return
  emit('submit', input.value)
  input.value = ''
}
</script>

<style scoped>
.chat-input {
  display: flex;
  gap: 8px;
  padding: 16px;
  background: var(--color-bg);
  border-top: 1px solid var(--color-border);
  border-radius: var(--radius);
}

.input-field {
  flex: 1;
  padding: 10px 14px;
  border: 1px solid var(--color-border);
  border-radius: var(--radius);
  font-size: 14px;
  resize: none;
  outline: none;
  font-family: inherit;
  line-height: 1.5;
}

.input-field:focus {
  border-color: var(--color-primary);
}

.input-field:disabled {
  background: var(--color-bg-secondary);
  cursor: not-allowed;
}

.btn-send {
  padding: 10px 20px;
  background: var(--color-primary);
  color: white;
  border-radius: var(--radius);
  font-size: 14px;
  font-weight: 500;
  align-self: flex-end;
}

.btn-send:hover:not(:disabled) {
  background: var(--color-primary-hover);
}

.btn-send:disabled {
  opacity: 0.6;
  cursor: not-allowed;
}
</style>
